from dataclasses import dataclass
from datetime import datetime,timezone
from pathlib import Path
import numpy as np,pandas as pd
from terminal2.config import ROOT_DIR
from terminal2.secret_lair.registry import REGISTRY_PATH,load_secret_lair_registry
from terminal2.secret_lair.pricing import PRICE_PATH,build_secret_lair_pricing_datasets
@dataclass(frozen=True)
class ExpansionBuildResult: datasets:dict[str,pd.DataFrame]
def _read(p):return pd.read_csv(p) if Path(p).exists() else pd.DataFrame()
def _current(cat,name):return Path(ROOT_DIR)/'data'/'warehouse'/'current'/cat/f'{name}.csv'
def _num(df,c,d=0):return pd.to_numeric(df[c],errors='coerce').fillna(d) if c in df else pd.Series(d,index=df.index,dtype=float)
def _clip(x):return pd.Series(x,index=getattr(x,'index',None)).clip(0,100).round(2)
def _risk_rating(s):return pd.cut(s,[-1,25,45,65,80,101],labels=['Low','Moderate','Elevated','High','Very High']).astype(str)
def _conf_rating(s):return pd.cut(s,[-1,35,55,70,85,101],labels=['Very Low','Low','Moderate','High','Very High']).astype(str)
def _universe(reg,current):
 cols=['investment_product_id','asset_class','secret_lair_id','product_name','drop_name','variant_name','finish','product_type','release_date','sale_start_date','sale_end_date','msrp_usd','current_price','franchise','universes_beyond','artist_names','card_count','availability_model','status']
 if reg.empty:return pd.DataFrame(columns=cols)
 f=reg.copy();f['investment_product_id']='SL-'+f['secret_lair_id'].astype(str);f['asset_class']='Secret Lair';f['product_name']=f['drop_name'].fillna('').astype(str)+' — '+f['variant_name'].fillna('').astype(str);f['product_type']=f['product_family'].fillna('drop').astype(str)
 cp=current[['secret_lair_id','market_price']].rename(columns={'market_price':'current_price'}) if not current.empty else pd.DataFrame(columns=['secret_lair_id','current_price']);f=f.merge(cp,on='secret_lair_id',how='left')
 for c in cols:
  if c not in f:f[c]=pd.NA
 return f[cols]
def _features(u,returns,coverage):
 cols=['investment_product_id','asset_class','product_name','product_age_months','foil_flag','universes_beyond_flag','artist_count','card_count','msrp_usd','current_price','premium_to_msrp','sale_window_days','limited_sale_flag','observation_count','source_count','history_span_days','return_30d','return_90d','return_365d','annualized_return','drawdown_from_peak','metadata_completeness','liquidity_score','volatility_proxy']
 if u.empty:return pd.DataFrame(columns=cols)
 f=u.copy();rcols=[c for c in ['secret_lair_id','return_30d','return_90d','return_365d','annualized_return','drawdown_from_peak','observation_count'] if c in returns];ccols=[c for c in ['secret_lair_id','source_count','history_span_days'] if c in coverage]
 if rcols:f=f.merge(returns[rcols],on='secret_lair_id',how='left')
 if ccols:f=f.merge(coverage[ccols],on='secret_lair_id',how='left')
 rel=pd.to_datetime(f['release_date'],errors='coerce');f['product_age_months']=((pd.Timestamp.now().normalize()-rel).dt.days/30.4375).clip(lower=0);f['foil_flag']=f['finish'].astype(str).str.lower().eq('foil');f['universes_beyond_flag']=f['universes_beyond'].astype(str).str.lower().isin(['true','1','yes']);f['artist_count']=f['artist_names'].fillna('').astype(str).map(lambda x:len([a for a in x.replace('|',',').split(',') if a.strip()]));f['card_count']=pd.to_numeric(f['card_count'],errors='coerce');f['msrp_usd']=pd.to_numeric(f['msrp_usd'],errors='coerce');f['current_price']=pd.to_numeric(f['current_price'],errors='coerce');f['premium_to_msrp']=np.where(f['msrp_usd']>0,f['current_price']/f['msrp_usd']-1,np.nan)
 start=pd.to_datetime(f['sale_start_date'],errors='coerce');end=pd.to_datetime(f['sale_end_date'],errors='coerce');f['sale_window_days']=(end-start).dt.days;f['limited_sale_flag']=f['availability_model'].fillna('').astype(str).str.lower().isin(['time-boxed','limited','limited sale'])
 meta=['drop_name','variant_name','finish','release_date','msrp_usd','franchise','artist_names','card_count'];f['metadata_completeness']=f[meta].notna().mean(axis=1)*100;f['observation_count']=_num(f,'observation_count');f['source_count']=_num(f,'source_count');f['history_span_days']=_num(f,'history_span_days');f['liquidity_score']=_clip(np.minimum(f['observation_count']/12*60,60)+np.minimum(f['source_count']/3*25,25)+np.minimum(f['history_span_days']/365*15,15));f['volatility_proxy']=pd.concat([_num(f,'return_30d'),_num(f,'return_90d'),_num(f,'return_365d')],axis=1).std(axis=1).fillna(0)
 for c in cols:
  if c not in f:f[c]=pd.NA
 return f[cols]
def _coverage(u,feat):
 cols=['investment_product_id','asset_class','product_name','registry_available','pricing_available','history_available','metadata_available','available_component_count','model_coverage_score','coverage_status']
 if u.empty:return pd.DataFrame(columns=cols)
 f=feat[['investment_product_id','metadata_completeness','observation_count','history_span_days','current_price']].merge(u[['investment_product_id','asset_class','product_name']],on='investment_product_id');f['registry_available']=True;f['pricing_available']=_num(f,'current_price').gt(0);f['history_available']=_num(f,'observation_count').ge(2);f['metadata_available']=_num(f,'metadata_completeness').ge(70);f['available_component_count']=f[['registry_available','pricing_available','history_available','metadata_available']].sum(axis=1);f['model_coverage_score']=f['available_component_count']/4*100;f['coverage_status']=np.select([f['model_coverage_score']>=100,f['model_coverage_score']>=75,f['model_coverage_score']>=50],['Complete','Strong','Partial'],default='Insufficient');return f[cols]
def _risk(feat):
 cols=['investment_product_id','asset_class','product_name','overall_risk_score','risk_rating','volatility_risk','liquidity_risk','drawdown_risk','data_risk','premium_risk']
 if feat.empty:return pd.DataFrame(columns=cols)
 f=feat[['investment_product_id','asset_class','product_name']].copy();vol=_clip(_num(feat,'volatility_proxy',.5)/.75*100);liq=_clip(100-_num(feat,'liquidity_score'));dd=_clip(_num(feat,'drawdown_from_peak',-.4).abs()*100);data=_clip(100-(_num(feat,'metadata_completeness')*.45+np.minimum(_num(feat,'observation_count')/12*100,100)*.55));prem=_clip(np.maximum(_num(feat,'premium_to_msrp')-4,0)/6*100);overall=_clip(vol*.2+liq*.25+dd*.2+data*.25+prem*.1);f['overall_risk_score']=overall;f['risk_rating']=_risk_rating(overall);f['volatility_risk']=vol;f['liquidity_risk']=liq;f['drawdown_risk']=dd;f['data_risk']=data;f['premium_risk']=prem;return f[cols]
def _confidence(feat,cov):
 cols=['investment_product_id','asset_class','product_name','overall_confidence_score','confidence_rating','price_history_score','metadata_score','coverage_score','source_diversity_score']
 if feat.empty:return pd.DataFrame(columns=cols)
 f=feat[['investment_product_id','asset_class','product_name']].copy();hist=_clip(np.minimum(_num(feat,'observation_count')/12*70,70)+np.minimum(_num(feat,'history_span_days')/365*30,30));meta=_clip(_num(feat,'metadata_completeness'));cv=cov.set_index('investment_product_id')['model_coverage_score'].reindex(feat['investment_product_id']).fillna(0).reset_index(drop=True);src=_clip(np.minimum(_num(feat,'source_count')/3*100,100));overall=_clip(hist*.35+meta*.25+cv*.25+src*.15);f['overall_confidence_score']=overall;f['confidence_rating']=_conf_rating(overall);f['price_history_score']=hist;f['metadata_score']=meta;f['coverage_score']=cv.values;f['source_diversity_score']=src;return f[cols]
def _scores(feat,risk,conf):
 cols=['investment_product_id','asset_class','product_name','investment_score','risk_adjusted_score','momentum_score','scarcity_score','ip_artist_score','value_score','liquidity_score','data_confidence_score']
 if feat.empty:return pd.DataFrame(columns=cols)
 f=feat[['investment_product_id','asset_class','product_name']].copy();mom=_clip(50+_num(feat,'return_30d')*80+_num(feat,'return_90d')*50+_num(feat,'return_365d')*30);scar=_clip(np.minimum(_num(feat,'product_age_months')/36*40,40)+feat['limited_sale_flag'].astype(int)*30+feat['foil_flag'].astype(int)*15+np.minimum(_num(feat,'premium_to_msrp').clip(lower=0)/3*15,15));ip=_clip(feat['universes_beyond_flag'].astype(int)*45+np.minimum(_num(feat,'artist_count')/3*35,35)+np.minimum(_num(feat,'card_count')/10*20,20));val=_clip(70-_num(feat,'premium_to_msrp')*10+_num(feat,'annualized_return')*80);liq=_clip(_num(feat,'liquidity_score'));cf=conf.set_index('investment_product_id')['overall_confidence_score'].reindex(feat['investment_product_id']).fillna(0).reset_index(drop=True);score=_clip(mom*.25+scar*.22+ip*.18+val*.15+liq*.10+cf*.10);rs=risk.set_index('investment_product_id')['overall_risk_score'].reindex(feat['investment_product_id']).fillna(100).reset_index(drop=True);f['investment_score']=score;f['risk_adjusted_score']=_clip(score-(rs-50)*.35);f['momentum_score']=mom;f['scarcity_score']=scar;f['ip_artist_score']=ip;f['value_score']=val;f['liquidity_score']=liq;f['data_confidence_score']=cf.values;return f[cols]
def _recommend(scores,risk,conf,cov):
 cols=['investment_product_id','asset_class','product_name','recommendation','recommendation_score','investment_score','risk_adjusted_score','overall_confidence_score','overall_risk_score','coverage_status']
 if scores.empty:return pd.DataFrame(columns=cols)
 f=scores.merge(risk[['investment_product_id','overall_risk_score']],on='investment_product_id').merge(conf[['investment_product_id','overall_confidence_score']],on='investment_product_id').merge(cov[['investment_product_id','coverage_status','model_coverage_score']],on='investment_product_id');f['recommendation_score']=_clip(f['risk_adjusted_score']*.7+f['overall_confidence_score']*.3);ins=(f['overall_confidence_score']<35)|(f['model_coverage_score']<50);f['recommendation']=np.select([ins,f['recommendation_score']>=78,f['recommendation_score']>=66,f['recommendation_score']>=54,f['recommendation_score']>=42],['Insufficient Data','Strong Buy','Buy','Watch','Hold'],default='Avoid');return f[cols]
def _factors(scores,risk):
 cols=['investment_product_id','asset_class','product_name','factor_code','factor_group','factor_value','factor_score','factor_direction']
 if scores.empty:return pd.DataFrame(columns=cols)
 j=scores.merge(risk[['investment_product_id','overall_risk_score']],on='investment_product_id');spec=[('momentum','return','momentum_score','positive'),('scarcity','supply','scarcity_score','positive'),('ip_artist','demand','ip_artist_score','positive'),('value','valuation','value_score','positive'),('liquidity','market','liquidity_score','positive'),('risk','risk','overall_risk_score','negative')];rows=[]
 for _,r in j.iterrows():
  for code,grp,col,d in spec:rows.append({'investment_product_id':r['investment_product_id'],'asset_class':r['asset_class'],'product_name':r['product_name'],'factor_code':code,'factor_group':grp,'factor_value':r[col],'factor_score':r[col],'factor_direction':d})
 return pd.DataFrame(rows,columns=cols)
def _buy(rec):
 cols=list(rec.columns)+['buy_list_rank']
 if rec.empty:return pd.DataFrame(columns=cols)
 f=rec[rec['recommendation'].isin(['Strong Buy','Buy','Watch'])].sort_values(['recommendation_score','overall_confidence_score','overall_risk_score'],ascending=[False,False,True]).head(50).copy();f['buy_list_rank']=range(1,len(f)+1);return f[cols]
def _boosters():
 rec=_read(_current('intelligence','intelligence_recommendations'))
 if rec.empty:return pd.DataFrame(columns=['investment_product_id','asset_class','product_name','product_type','current_price']),pd.DataFrame(columns=['investment_product_id','asset_class','product_name','recommendation','recommendation_score','overall_confidence_score','overall_risk_score'])
 prod=pd.DataFrame({'investment_product_id':rec['investment_product_id'],'asset_class':'Booster Box','product_name':rec.get('box_name',rec['investment_product_id']),'product_type':rec.get('product_type','Booster Product'),'current_price':rec.get('current_price',pd.NA)});recs=pd.DataFrame({'investment_product_id':rec['investment_product_id'],'asset_class':'Booster Box','product_name':rec.get('box_name',rec['investment_product_id']),'recommendation':rec['recommendation'],'recommendation_score':rec['recommendation_score'],'overall_confidence_score':rec['overall_confidence_score'],'overall_risk_score':rec['overall_risk_score']});return prod,recs
def build_secret_lair_intelligence_expansion(registry_path=REGISTRY_PATH,price_path=PRICE_PATH):
 reg,_=load_secret_lair_registry(registry_path);pricing=build_secret_lair_pricing_datasets(registry_path=registry_path,price_path=price_path).datasets;u=_universe(reg,pricing['secret_lair_current_prices']);feat=_features(u,pricing['secret_lair_returns'],pricing['secret_lair_price_coverage']);cov=_coverage(u,feat);risk=_risk(feat);conf=_confidence(feat,cov);scores=_scores(feat,risk,conf);rec=_recommend(scores,risk,conf,cov);factors=_factors(scores,risk);buy=_buy(rec);bp,br=_boosters();sp=u[['investment_product_id','asset_class','product_name','product_type','current_price']].copy();up=pd.concat([bp,sp],ignore_index=True).drop_duplicates('investment_product_id');ur=pd.concat([br,rec[['investment_product_id','asset_class','product_name','recommendation','recommendation_score','overall_confidence_score','overall_risk_score']]],ignore_index=True).drop_duplicates('investment_product_id');ub=ur[ur['recommendation'].isin(['Strong Buy','Buy','Watch'])].sort_values(['recommendation_score','overall_confidence_score','overall_risk_score'],ascending=[False,False,True]).head(100).copy();ub['unified_rank']=range(1,len(ub)+1);rows=[]
 for cls,g in ur.groupby('asset_class'):
  products=up[up['asset_class'].eq(cls)];rows.append({'asset_class':cls,'product_count':len(products),'priced_product_count':int(pd.to_numeric(products['current_price'],errors='coerce').gt(0).sum()),'actionable_count':int(g['recommendation'].isin(['Strong Buy','Buy','Watch']).sum()),'average_recommendation_score':pd.to_numeric(g['recommendation_score'],errors='coerce').mean(),'average_confidence':pd.to_numeric(g['overall_confidence_score'],errors='coerce').mean(),'average_risk':pd.to_numeric(g['overall_risk_score'],errors='coerce').mean()})
 asset=pd.DataFrame(rows,columns=['asset_class','product_count','priced_product_count','actionable_count','average_recommendation_score','average_confidence','average_risk']);summary=pd.DataFrame([{'snapshot_date':datetime.now(timezone.utc).date().isoformat(),'asset_count':len(u),'priced_asset_count':int(_num(u,'current_price').gt(0).sum()) if not u.empty else 0,'actionable_count':int(rec['recommendation'].isin(['Strong Buy','Buy','Watch']).sum()) if not rec.empty else 0,'average_score':pd.to_numeric(scores.get('investment_score'),errors='coerce').mean() if not scores.empty else np.nan,'average_confidence':pd.to_numeric(conf.get('overall_confidence_score'),errors='coerce').mean() if not conf.empty else np.nan,'average_risk':pd.to_numeric(risk.get('overall_risk_score'),errors='coerce').mean() if not risk.empty else np.nan}])
 return ExpansionBuildResult({'secret_lair_investment_universe':u,'secret_lair_feature_matrix':feat,'secret_lair_risk_assessment':risk,'secret_lair_confidence_assessment':conf,'secret_lair_investment_scores':scores,'secret_lair_recommendations':rec,'secret_lair_recommendation_factors':factors,'secret_lair_executive_buy_list':buy,'secret_lair_model_coverage':cov,'secret_lair_intelligence_summary':summary,'unified_investment_products':up,'unified_investment_recommendations':ur,'unified_executive_buy_list':ub,'unified_asset_class_summary':asset})
