from __future__ import annotations
from dataclasses import dataclass
from datetime import datetime,timezone
import json
from pathlib import Path
import pandas as pd
from .config import MASTER_PRODUCTS_PATH,MASTER_HISTORY_PATH,PRODUCT_MAP_PATH,MASTER_ROOT
from .http_client import CachedHttpClient
from .normalize import canonical_name,infer_finish,infer_family,key,stable_id,variant_name
from .sources import official_records,tcgcsv_records,scryfall_cards

@dataclass(frozen=True)
class MasterDatabaseBuildResult:
 datasets:dict[str,pd.DataFrame];local_root:str

def _empty(cols):return pd.DataFrame(columns=list(cols))
def _num(v):
 try:return float(v)
 except Exception:return None

def _combine_records(official,tcg):
 frames=[x for x in (official,tcg) if x is not None and not x.empty]
 if not frames:return pd.DataFrame(columns=["source_name","source_record_id","source_product_name","source_url","group_name","published_on","market_price","low_price","tcgplayer_product_id","tcgcsv_group_id","tcgcsv_category_id","raw_json"])
 combined=pd.concat([frame.dropna(axis=1,how="all") for frame in frames],ignore_index=True,sort=False)
 return combined.drop_duplicates(["source_name","source_record_id"])

def _canonicalize(records):
 product_rows=[];source_rows=[];review=[]
 if records.empty:return pd.DataFrame(),pd.DataFrame(),pd.DataFrame()
 records=records.copy();records["canonical_name"]=records["source_product_name"].map(canonical_name);records["finish"]=records["source_product_name"].map(infer_finish);records["product_family"]=records["source_product_name"].map(infer_family);records["canonical_key"]=records.apply(lambda r:key(f"{r['canonical_name']}|{r['finish']}|{r['product_family']}"),axis=1)
 for ckey,group in records.groupby("canonical_key",dropna=False):
  names=group["canonical_name"].dropna().astype(str);name=names.mode().iloc[0] if not names.empty else ""
  finish=group["finish"].mode().iloc[0] if not group.empty else "unknown";family=group["product_family"].mode().iloc[0] if not group.empty else "drop"
  sl_id=stable_id("SL",f"{name}|{finish}|{family}")
  official=group[group["source_name"].eq("official_secret_lair")];tcg=group[group["source_name"].eq("tcgcsv")]
  confidence=95 if not official.empty and not tcg.empty else 75 if not tcg.empty else 60
  release=next((x for x in group["published_on"].astype(str) if x and x!="nan"),"")
  product_rows.append({"secret_lair_id":sl_id,"product_name":f"{name} — {variant_name(group.iloc[0]['source_product_name'])}","drop_name":name,"variant_name":variant_name(group.iloc[0]["source_product_name"]),"finish":finish,"product_family":family,"release_date":release,"sale_start_date":"","sale_end_date":"","msrp_usd":None,"currency":"USD","franchise":"","ip_category":"","universes_beyond":False,"artist_names":"","card_count":None,"superdrop_name":"","event_type":"drop","availability_model":"limited sale","status":"historical" if release else "unknown","official_url":official.iloc[0]["source_url"] if not official.empty else "","source_name":"official_secret_lair|tcgcsv" if not official.empty and not tcg.empty else group.iloc[0]["source_name"],"source_record_id":"|".join(group["source_record_id"].astype(str)),"notes":"Generated by Master Secret Lair Database","source_confidence":confidence})
  for _,r in group.iterrows():source_rows.append({"source_name":r["source_name"],"source_record_id":r["source_record_id"],"source_product_name":r["source_product_name"],"source_url":r["source_url"],"canonical_name":name,"match_status":"accepted" if confidence>=75 else "review","secret_lair_id":sl_id,"match_confidence":confidence,"raw_json":r.get("raw_json","")})
  if confidence<75:review.append({"review_id":stable_id("SLR",f"{sl_id}|low_confidence"),"review_type":"low_confidence","severity":"Warning","source_name":group.iloc[0]["source_name"],"source_record_id":group.iloc[0]["source_record_id"],"product_name":name,"message":"Only one weak source supports this product identity."})
  if finish=="unknown":review.append({"review_id":stable_id("SLR",f"{sl_id}|unknown_finish"),"review_type":"unknown_finish","severity":"Warning","source_name":group.iloc[0]["source_name"],"source_record_id":group.iloc[0]["source_record_id"],"product_name":name,"message":"Finish could not be determined from the source product name."})
 products=pd.DataFrame(product_rows).drop_duplicates("secret_lair_id");sources=pd.DataFrame(source_rows);reviews=pd.DataFrame(review)
 return products,sources,reviews

def _prices(records,sources):
 cols=["secret_lair_id","source_name","observation_date","market_price","low_price","tcgplayer_product_id","tcgcsv_group_id","tcgcsv_category_id","source_record_id"]
 if records.empty or sources.empty:return _empty(cols)
 tcg=records[records["source_name"].eq("tcgcsv")].copy()
 if tcg.empty:return _empty(cols)
 mapping=sources[["source_name","source_record_id","secret_lair_id"]]
 tcg=tcg.merge(mapping,on=["source_name","source_record_id"],how="left")
 today=datetime.now(timezone.utc).date().isoformat();tcg["observation_date"]=today;tcg["market_price"]=pd.to_numeric(tcg["market_price"],errors="coerce");tcg["low_price"]=pd.to_numeric(tcg["low_price"],errors="coerce")
 return tcg[cols].dropna(subset=["secret_lair_id"]).drop_duplicates(["secret_lair_id","source_name"])

def _append_history(current):
 cols=["observation_date","secret_lair_id","source_name","market_price","low_price","source_record_id"]
 previous=pd.read_csv(MASTER_HISTORY_PATH) if MASTER_HISTORY_PATH.exists() else _empty(cols)
 add=current[[c for c in cols if c in current]].copy() if not current.empty else _empty(cols)
 combined=pd.concat([x for x in (previous,add) if not x.empty],ignore_index=True) if (not previous.empty or not add.empty) else _empty(cols)
 if not combined.empty:combined=combined.drop_duplicates(["observation_date","secret_lair_id","source_name"],keep="last").sort_values(["secret_lair_id","observation_date"])
 MASTER_ROOT.mkdir(parents=True,exist_ok=True);combined.to_csv(MASTER_HISTORY_PATH,index=False);return combined

def _product_map(records,sources):
 cols=["secret_lair_id","tcgplayer_product_id","tcgcsv_category_id","tcgcsv_group_id","product_name","match_confidence"]
 if records.empty:return _empty(cols)
 tcg=records[records["source_name"].eq("tcgcsv")].merge(sources[["source_name","source_record_id","secret_lair_id","canonical_name","match_confidence"]],on=["source_name","source_record_id"],how="left")
 if tcg.empty:return _empty(cols)
 out=pd.DataFrame({"secret_lair_id":tcg["secret_lair_id"],"tcgplayer_product_id":tcg["tcgplayer_product_id"],"tcgcsv_category_id":tcg["tcgcsv_category_id"],"tcgcsv_group_id":tcg["tcgcsv_group_id"],"product_name":tcg["source_product_name"],"match_confidence":tcg["match_confidence"]})
 return out.dropna(subset=["secret_lair_id","tcgplayer_product_id"]).drop_duplicates(["secret_lair_id","tcgplayer_product_id"])

def build_master_secret_lair_database(*,refresh=False,max_tcgcsv_groups=None,client=None):
 client=client or CachedHttpClient();official=official_records(client,refresh=refresh);tcg=tcgcsv_records(client,refresh=refresh,max_groups=max_tcgcsv_groups);cards=scryfall_cards(client,refresh=refresh);records=_combine_records(official,tcg);products,sources,reviews=_canonicalize(records);current=_prices(records,sources);history=_append_history(current);pmap=_product_map(records,sources)
 MASTER_ROOT.mkdir(parents=True,exist_ok=True);products.to_csv(MASTER_PRODUCTS_PATH,index=False);pmap.to_csv(PRODUCT_MAP_PATH,index=False)
 current_count=int(current["market_price"].notna().sum()) if not current.empty else 0;ready=int(((products["source_confidence"]>=75) & products["finish"].ne("unknown")).sum()) if not products.empty else 0
 summary=pd.DataFrame([{"snapshot_date":datetime.now(timezone.utc).date().isoformat(),"source_product_count":len(records),"canonical_product_count":len(products),"current_price_count":current_count,"historical_observation_count":len(history),"review_count":len(reviews),"registry_ready_count":ready,"official_source_count":len(official),"tcgcsv_source_count":len(tcg),"scryfall_card_count":len(cards)}])
 return MasterDatabaseBuildResult({"master_secret_lair_products":products,"master_secret_lair_prices_current":current,"master_secret_lair_price_history":history,"master_secret_lair_source_records":sources,"master_secret_lair_card_metadata":cards,"master_secret_lair_product_map":pmap,"master_secret_lair_review_queue":reviews,"master_secret_lair_summary":summary},str(MASTER_ROOT))
