from pathlib import Path
import pandas as pd
from terminal2.secret_lair.registry import REGISTRY_COLUMNS
from terminal2.secret_lair.pricing import PRICE_COLUMNS
from .config import MASTER_ROOT

PROPOSED_REGISTRY_PATH=MASTER_ROOT/"proposed_secret_lair_registry.csv"
PROPOSED_PRICES_PATH=MASTER_ROOT/"proposed_secret_lair_price_observations.csv"

def export_master_database_import_files(datasets,*,minimum_confidence=75):
 products=datasets["master_secret_lair_products"].copy()
 products=products[pd.to_numeric(products.get("source_confidence"),errors="coerce").fillna(0)>=minimum_confidence]
 for c in REGISTRY_COLUMNS:
  if c not in products:products[c]=pd.NA
 registry=products[list(REGISTRY_COLUMNS)].copy()
 prices=datasets["master_secret_lair_prices_current"].copy()
 rename={"source_record_id":"source_record_id"}
 for c in PRICE_COLUMNS:
  if c not in prices:prices[c]=pd.NA
 prices["currency"]="USD";prices["price_data_quality"]="automated_master_database";prices["source_url"]="";prices["listing_count"]=pd.NA;prices["sales_count_30d"]=pd.NA;prices["notes"]="Generated by Terminal 2.9.7"
 prices=prices[list(PRICE_COLUMNS)].copy()
 MASTER_ROOT.mkdir(parents=True,exist_ok=True);registry.to_csv(PROPOSED_REGISTRY_PATH,index=False);prices.to_csv(PROPOSED_PRICES_PATH,index=False)
 return {"registry_path":str(PROPOSED_REGISTRY_PATH),"registry_rows":len(registry),"prices_path":str(PROPOSED_PRICES_PATH),"price_rows":len(prices)}
